# Generated by Django 3.2.13 on 2022-06-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('subject', models.CharField(choices=[('general_query', 'GENERAL QUERY'), ('account_issue', 'ACCOUNT ISSUE'), ('product_enquiry', 'PRODUCT ENQUIRY'), ('order', 'ORDER'), ('refund_request', 'REFUND REQUEST')], default='general_query', max_length=100)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
